import { StyleSheet } from '@react-pdf/renderer'

export const colors = {
  // Primary brand
  primary: '#2d6a4f',
  accent: '#52b788',
  light: '#d8f3dc',
  text: '#1b1b1b',
  muted: '#666666',
  border: '#cccccc',
  pageBackground: '#ffffff',

  // Page-type accent colors (used for top bands and h1 overrides)
  orange: '#f97316',
  coral: '#f4845f',
  sky: '#0ea5e9',
  sunshine: '#f59e0b',
  purple: '#7c3aed',
  pink: '#ec4899',
  teal: '#0891b2',
  amber: '#d97706',
  rose: '#e11d48',
  navy: '#2563eb',
  gold: '#ca8a04',

  // Soft fills matching band colors
  lightOrange: '#fff7ed',
  lightSky: '#f0f9ff',
  lightSunshine: '#fffbeb',
  lightPurple: '#f5f3ff',
  lightPink: '#fdf2f8',
  lightTeal: '#f0fdfa',
  lightAmber: '#fffbeb',
  lightNavy: '#eff6ff',
}

export const styles = StyleSheet.create({
  page: {
    backgroundColor: colors.pageBackground,
    fontFamily: 'Nunito',
    padding: 36,
    fontSize: 11,
    color: colors.text,
  },
  footer: {
    position: 'absolute',
    bottom: 18,
    left: 36,
    right: 36,
    flexDirection: 'row',
    justifyContent: 'space-between',
    fontSize: 8,
    color: colors.muted,
    borderTopWidth: 0.5,
    borderTopColor: colors.border,
    paddingTop: 4,
  },
  coverPage: {
    backgroundColor: colors.pageBackground,
    padding: 0,
  },
  h1: {
    fontFamily: 'Nunito-Bold',
    fontSize: 28,
    color: colors.primary,
    marginBottom: 8,
  },
  h2: {
    fontFamily: 'Nunito-Bold',
    fontSize: 18,
    color: colors.primary,
    marginBottom: 6,
  },
  h3: {
    fontFamily: 'Nunito-Bold',
    fontSize: 13,
    color: colors.primary,
    marginBottom: 4,
  },
  body: {
    fontSize: 11,
    lineHeight: 1.5,
    color: colors.text,
  },
  smallText: {
    fontSize: 9,
    color: colors.muted,
    lineHeight: 1.4,
  },
  calloutBox: {
    backgroundColor: colors.light,
    borderRadius: 6,
    padding: 10,
    marginBottom: 10,
    borderLeftWidth: 3,
    borderLeftColor: colors.accent,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 5,
  },
  checkbox: {
    width: 14,
    height: 14,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 2,
    marginRight: 7,
    marginTop: 1,
    flexShrink: 0,
  },
  checkboxLabel: {
    fontSize: 11,
    flex: 1,
    lineHeight: 1.4,
  },
  drawingBox: {
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 6,
    borderStyle: 'dashed',
    height: 140,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
  },
  drawingBoxLabel: {
    fontSize: 10,
    color: colors.muted,
    textAlign: 'center',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    borderBottomWidth: 2,
    borderBottomColor: colors.accent,
    paddingBottom: 6,
  },
  emoji: {
    fontSize: 22,
    marginRight: 8,
  },
  badgeCircle: {
    width: 90,
    height: 90,
    borderRadius: 45,
    borderWidth: 2.5,
    borderColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    margin: 10,
    padding: 8,
  },
  badgeText: {
    fontSize: 9,
    fontFamily: 'Nunito-Bold',
    color: colors.primary,
    textAlign: 'center',
  },
  bingoCell: {
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 4,
  },
  bingoCellText: {
    fontSize: 8,
    textAlign: 'center',
    color: colors.text,
  },
  freeCellText: {
    fontSize: 9,
    fontFamily: 'Nunito-Bold',
    color: colors.primary,
    textAlign: 'center',
  },
  starBox: {
    backgroundColor: '#fff9c4',
    borderWidth: 1,
    borderColor: '#f9c922',
    borderRadius: 6,
    padding: 8,
    marginBottom: 8,
  },
  carBox: {
    backgroundColor: '#e8f4fd',
    borderWidth: 1,
    borderColor: '#90caf9',
    borderRadius: 6,
    padding: 8,
    marginBottom: 8,
  },
  thinkBox: {
    backgroundColor: '#f3e8ff',
    borderWidth: 1,
    borderColor: '#c084fc',
    borderRadius: 6,
    padding: 8,
    marginBottom: 8,
  },
  personalizationBox: {
    backgroundColor: '#fff0f3',
    borderWidth: 1,
    borderColor: '#ffb3c1',
    borderRadius: 6,
    padding: 8,
    marginBottom: 8,
  },
  twoColumn: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  halfWidth: {
    width: '50%',
    paddingRight: 8,
    marginBottom: 10,
  },
  certificateBorder: {
    borderWidth: 4,
    borderColor: colors.accent,
    borderRadius: 12,
    padding: 30,
    margin: 20,
  },
  signatureLine: {
    borderBottomWidth: 1,
    borderBottomColor: colors.text,
    marginTop: 20,
    marginBottom: 4,
    width: '70%',
  },
  signatureLabel: {
    fontSize: 9,
    color: colors.muted,
  },
  // Colored top band — place as first child with position absolute
  pageBand: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 10,
  },
})
